### ISSUE TITLE
Weird issue with finalize and custom renderer

### ISSUE THREAD

**Issue by mamantoha** [amauryt/cr-cmark-gfm#9]
Code to reproduce:

```crystal
# issue.cr
require "cmark"

class Renderer < Cmark::HTMLRenderer
end

1000.times do |i|
  puts i

  content = File.read("README.md")

  options = Cmark::Option.flags(Unsafe, Nobreaks, ValidateUTF8)
  extensions = Cmark::Extension.flags(Table, Strikethrough, Autolink, Tagfilter, Tasklist)

  node = Cmark.parse_gfm(content, options)
  renderer = Renderer.new(options, extensions)
  markdown = renderer.render(node)
end
```

`README.md` is taken from <https://raw.githubusercontent.com/mamantoha/crest/master/README.md>

The output is like this:

```
Invalid memory access (signal 7) at address 0x0
[0x5600d11f4456] *Exception::CallStack::print_backtrace:(Int32 | Nil) +118
[0x5600d11e510a] ~procProc(Int32, Pointer(LibC::SiginfoT), Pointer(Void), Nil) +330
[0x7f8ee31b9420] ???
[0x5600d12f8fdf] GC_malloc_kind +223
[0x5600d12eb5b1] GC_realloc +209
[0x5600d1212536] *GC::realloc<Pointer(Void), UInt64>:Pointer(Void) +6
[0x5600d11d3119] __crystal_realloc64 +25
[0x5600d11eaec8] *Pointer(UInt8) +136
[0x5600d1211437] *String::Builder#resize_to_capacity<Int32>:Pointer(UInt8) +23
[0x5600d121138c] *String::Builder#write<Slice(UInt8)>:Nil +156
[0x5600d1211233] *String::Builder +131
[0x5600d11fca42] *String#to_s<String::Builder>:Nil +66
[0x5600d1211eeb] *String::Builder +107
[0x5600d120d7d8] *String#gsub<Hash(Char, String)>:String +568
[0x5600d12b49d8] *Renderer +40
[0x5600d12b5309] *Renderer +57
[0x5600d12b3c90] *Renderer +1792
[0x5600d11d3070] __crystal_main +1616
[0x5600d12b9536] *Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil +6
[0x5600d12b93ac] *Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32 +44
[0x5600d11de506] main +6
[0x7f8ee2f600b3] __libc_start_main +243
[0x5600d11d295e] _start +46
[0x0] ???
```

I investigate and found the issue is from `Cmark::Node#finalize` method. If you comment on it everything runs fine.
Right now I have no idea how to fix this.

I submit this issue to keep track of it.

**Comment by amauryt** [comment]
Hi, @mamantoha. I can confirm that your example gives an "Invalid memory access".

Indeed this is a weird issue. As far as I know, this is due to the specifics of garbage collection in Crystal while reading the file contents within your loop. According to the Crystal [documentation on concurrency](https://crystal-lang.org/reference/guides/concurrency.html):

> The Event Loop, which is just another fiber, being in charge of async tasks, like for example files, sockets, pipes, signals and timers (like doing a sleep)

This seems to create a problem for garbage collection across iterations, but not because of the access to the node pointer within the `finalize` method as you can put code that does not access the underlying C pointer in this method (e.g., `puts "finalize"`) and the issue stills persists. I'm not certain of the underlying mechanism, but I guess that it is because the garbage collector is working at different moments and/or contexts when collecting the contents of the node (the file) and the node itself for a given iteration.

For you specific example, and if this issue is blocking you, I see three workarounds:

1. The trivial but most likely less useful is to move the file reading outside and before the loop so the `contents` variable is set only once (perhaps you use the same contents but with different rendering options).

```crystal
# ...
content = File.read("README.md") # Move this line outside the loop
1000.times do |i|
  #...
end
```

2.  Another option to use force garbage collection at the end of a iteration.

```crystal
# ...
1000.times do |i|
  #...
  GC.collect # Force garbage collection
end
```

3.  The last workaround I see is to disable and enable garbage collection around the core of the loop, paying attention to initialize variables only once outside when appropriate (for instance, if `options`, `extensions` `renderer` never change from iteration to iteration move them outside of the loop)

```crystal
# ...
GC.disable
1000.times do |i|
  #...
end
GC.enable
```

Each workaround has potential issues so I would use profiling to see if these negatively affect your app.

In case you find a better solution as always a PR or a comment below with it is more than welcome!

**Comment by mamantoha** [comment]
Hi @amauryt . Thanks for the explanation. The third workaround helps to prevent "Invalid memory access" or any other issue.

The next code is close to my real use case:

```
require "kemal"
require "cmark"

class Renderer < Cmark::HTMLRenderer
end

get "/" do
  GC.disable

  content = File.read("README.md")

  options = Cmark::Option.flags(Unsafe, Nobreaks, ValidateUTF8)
  extensions = Cmark::Extension.flags(Table, Strikethrough, Autolink, Tagfilter, Tasklist)

  node = Cmark.parse_gfm(content, options)
  renderer = Renderer.new(options, extensions)
  markdown = renderer.render(node)

  GC.enable

  markdown
end

Kemal.run
```

Tested few times with:

```
ab -n 10000 -c 100 http://localhost:3000/
```

Used memory doesn't grow. So this is fine enough.
